repos:
  - repo: builtin
    hooks:
      # General
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args: [--maxkb=50000]
      # Checks if configs parse
      - id: check-toml
      - id: check-yaml
# - repo: local
#   hooks:
#     - id: format
#       name: format
#       language: system
#       pass_filenames: false
#       entry: just fmt
