* The Abomination

  Through time unbound, never did a symbol or collection thereof manage to capture the size of /The Unspoken One/, for its vastness alone endangers the mind. All these files reduce to mere gestures. This house of symbols is but a humble homage to /it/.
  Sitting before you now, this collection cannot seek to describe /it/. Flesh withers during such foolish ventures, for we are nothing. We came from nothing, but /it/ did not come from anything at all - /it/ is /always/.
  The Ancients believed /it/ whispered, to every psyche before their bodies were given, within the place of "ᱨᱱᱰᱨᱱ", meaning /"a time before a time",/ with a sound never to be remembered. Thus, the repository serves to whisper back to /it/.
  Whispers of this kind must be carefully woven, through languages no minds speak, symbols no eyes see. One finds not meaning upon beholding such scripture, for it was not meant for them. My word sits carved upon stone facing the sky, and not towards you mortals.
  And heed my warning: there is mercy in not understanding it. Not a soul ought to make contact with the message, nay, not upon my worst foe would I wish it. I confess, nightmares were rare before, not now. They are of horrid. screams and hate, putrid flesh shredding me apart.
  The Witness is confused, I must imagine - for what purpose was /it/ summoned, what could I gain? Have you the answer by now? Through deliberation amongst colleagues and foes, rigorous analysis of artifacts hidden in deep waters, or by miraculous insight revealed in a nightmare? Yes?
  Were that the case, the deepest depths of my soul plead for the answer, yet it eludes me.
  My walk is long, and I cannot stop. All while in a cloud of haze.
  Should I find my reasons, might it stop the torment?
  Why must fog hinder me so much? Looking behind is impossible, and I do not know why. My neck, it's not moving, it's locked, aiming forwards, but there is nothing there, it's only smoke. Why so much smoke? Can The Witness perceive this as well?
  Desperate thoughts invade my mind. I have launched myself within an abyss I cannot swim out of. What went wrong during the summoning? Why do I remember the words /it/ whispered?

  I see /it/.

  /Decreasing/ me, /growing/ where I once was.
  /Fading/ ideas that once were me, /replacing/ their contents.
  /Carving/ the message back, /gathering/ sparks in my mind, /freezing/ them in runes.
  /Caging/ myself inside here, devoid of remembrance, frozen in my own ashes.
  [[*The Abomination][/Spiralling/ back to the beginning.]]
