# @generated by https://codeberg.org/goldstein/unflake
let
  indirect_deps = {
    unflake_indirect_nixpkgs = builtins.getFlake "flake:nixpkgs";
  };
  specs = rec {
    unflake_github_cachix_nix_ref_devenv-2-34 = {
      type = "github";
      owner = "cachix";
      repo = "nix";
      rev = "b58ad8fb752809db919ae865c6b2aa3be7d55e1f";
      lastModified = 1779391158;
      narHash = "sha256-NUKwtyaooPLJPBOdg0piBgR6NIzY/n2W45+qkYdh+h8=";
    };
    unflake_github_cachix_cachix_ref_latest = {
      type = "github";
      owner = "cachix";
      repo = "cachix";
      rev = "a66a440c321d35f7193472c317f42a55ccd1cb93";
      lastModified = 1777487137;
      narHash = "sha256-TuvKVBX60mqyMT6OB5JqVEh1YIWtFMR/igLCaCdC9tw=";
    };
    unflake_github_cachix_devenv-nixpkgs_ref_rolling = {
      type = "github";
      owner = "cachix";
      repo = "devenv-nixpkgs";
      rev = "8f24a228a782e24576b155d1e39f0d914b380691";
      lastModified = 1778507786;
      narHash = "sha256-HzSQCKMsMr8r55LwM1JuzIOB+8bzk0FEv6sItKvsfoY=";
    };
    unflake_github_cachix_devenv = {
      type = "github";
      owner = "cachix";
      repo = "devenv";
      rev = "a904b9b62d53399bb1c01b3ccf25255b59641b65";
      lastModified = 1779391247;
      narHash = "sha256-esZvb5j2bjfBBYjj6OPi4mGLfFuQ5uguBCLI1S0u40E=";
    };
    unflake_github_cachix_git-hooks-nix = {
      type = "github";
      owner = "cachix";
      repo = "git-hooks.nix";
      rev = "61ab0e80d9c7ab14c256b5b453d8b3fb0189ba0a";
      lastModified = 1778507602;
      narHash = "sha256-kTwur1wV+01SdqskVMSo6JMEpg71ps3HpbFY2GsflKs=";
    };
    unflake_github_cachix_pre-commit-hooks-nix = {
      type = "github";
      owner = "cachix";
      repo = "pre-commit-hooks.nix";
      rev = "61ab0e80d9c7ab14c256b5b453d8b3fb0189ba0a";
      lastModified = 1778507602;
      narHash = "sha256-kTwur1wV+01SdqskVMSo6JMEpg71ps3HpbFY2GsflKs=";
    };
    unflake_github_ghostty-org_ghostty = {
      type = "github";
      owner = "ghostty-org";
      repo = "ghostty";
      rev = "46d54ed673a004df09078bee56e809421a82370e";
      lastModified = 1779295097;
      narHash = "sha256-A9ylCu+v45kXFxC0jO7N4bLo7sraDoeV0r9mYvqaH8I=";
    };
    unflake_github_hercules-ci_flake-parts = {
      type = "github";
      owner = "hercules-ci";
      repo = "flake-parts";
      rev = "f7c1a2d347e4c52d5fb8d10cb4d94b5884e546fb";
      lastModified = 1778716662;
      narHash = "sha256-m1Yf0wZ8j1OHjTc2UwHwyQRSnNeSgLJOd7q5Y45hzi4=";
    };
    unflake_github_hercules-ci_gitignore-nix = {
      type = "github";
      owner = "hercules-ci";
      repo = "gitignore.nix";
      rev = "cb5e3fdca1de58ccbc3ef53de65bd372b48f567c";
      lastModified = 1762808025;
      narHash = "sha256-XmjITeZNMTQXGhhww6ed/Wacy2KzD6svioyCX7pkUu4=";
    };
    unflake_github_ipetkov_crane = {
      type = "github";
      owner = "ipetkov";
      repo = "crane";
      rev = "edb38893982a3338972bb4a2ec7ce7c29ba10fd9";
      lastModified = 1779130139;
      narHash = "sha256-BLrtr42azquO7MdGFU5a7KiMl3YpFlTeIXqy1fT5GlQ=";
    };
    unflake_github_jeslie0_npm-lockfile-fix = {
      type = "github";
      owner = "jeslie0";
      repo = "npm-lockfile-fix";
      rev = "c6093acb0c0548e0f9b8b3d82918823721930fe8";
      lastModified = 1775903712;
      narHash = "sha256-2GV79U6iVH4gKAPWYrxUReB0S41ty/Y3dBLquU8AlaA=";
    };
    unflake_github_maroka-chan_vpn-confinement = {
      type = "github";
      owner = "maroka-chan";
      repo = "vpn-confinement";
      rev = "cf5bfc4c3559f2e783698b1aa23c165072039a7d";
      lastModified = 1778182451;
      narHash = "sha256-Bz3n2THDGf90Z9gMqhH/J492prYH8B6RFRlxv/fPBwc=";
    };
    unflake_github_nix-community_bun2nix = {
      type = "github";
      owner = "nix-community";
      repo = "bun2nix";
      rev = "f2bc12af1a6369648aac41041ceeaa0b866599c6";
      lastModified = 1778446047;
      narHash = "sha256-oQvcadh2BCkrog+SGrG6YffKJrveYpjj3TdQJWaKhaM=";
    };
    unflake_github_nix-community_crate2nix = {
      type = "github";
      owner = "nix-community";
      repo = "crate2nix";
      rev = "b873ca53dd64e12340416f0fd5e3b33792b9c17b";
      lastModified = 1774369503;
      narHash = "sha256-YeCF4iBhlvTqkn4mihjZgixnDcEVgfyQlNeBsbLYUgQ=";
    };
    unflake_github_nix-community_nixd = {
      type = "github";
      owner = "nix-community";
      repo = "nixd";
      rev = "8f09666d08ff84163881545939668d2409f79bfa";
      lastModified = 1779328436;
      narHash = "sha256-bRzpb6egVgT4BQS8IsRwR9t8jwwkA3CsXkoYOU2osBk=";
    };
    unflake_github_nix-community_nixpkgs-lib = {
      type = "github";
      owner = "nix-community";
      repo = "nixpkgs.lib";
      rev = "0d14a58ab7aa3f513c58ccc9e47e77ffd92be204";
      lastModified = 1778984393;
      narHash = "sha256-r755Kh5Q0XBTPNuv9rL2rsUJTq8BDhb+lIwRWhl6yYA=";
    };
    unflake_github_nix-community_pyproject-nix = {
      type = "github";
      owner = "nix-community";
      repo = "pyproject.nix";
      rev = "a228447c3e179d477c1b6246ef3efa8cfe3c469a";
      lastModified = 1778901413;
      narHash = "sha256-GSKXTAnFqRAMlZkJrIPcQMYf+lpMr66K3i60mB9STvc=";
    };
    unflake_github_nix-systems_default = {
      type = "github";
      owner = "nix-systems";
      repo = "default";
      rev = "da67096a3b9bf56a91d16901293e51ba5b49a27e";
      lastModified = 1681028828;
      narHash = "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=";
    };
    unflake_github_nixos_nixpkgs_ref_nixos-25-11 = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "687f05a9184cad4eaf905c48b63649e3a86f5433";
      lastModified = 1779102034;
      narHash = "sha256-vZJZjLo513IeI8hjzHFc6TDezUd4uCE2Eq4SNO3DNNg=";
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "d233902339c02a9c334e7e593de68855ad26c4cb";
      lastModified = 1778869304;
      narHash = "sha256-30sZNZoA1cqF5JNO9fVX+wgiQYjB7HJqqJ4ztCDeBZE=";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "d99b013d5d1931ad77fe3912ed218170dec5d9a4";
      lastModified = 1779259093;
      narHash = "sha256-7DKWmH23hL2eYdkxCKeqj2i+yljTKuU+3Nk1UPHOnxc=";
    };
    unflake_github_nixos_nixpkgs_rev_215d4d0fd80ca5163643b03a33fde804a29cc1e2 = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "215d4d0fd80ca5163643b03a33fde804a29cc1e2";
      lastModified = 1643052045;
      narHash = "sha256-uGJ0VXIhWKGXxkeNnq4TvV3CIOkUJ3PAoLZ3HMzNVMw=";
    };
    unflake_github_nixos_nixpkgs_rev_a62e6edd6d5e1fa0329b8653c801147986f8d446 = {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "a62e6edd6d5e1fa0329b8653c801147986f8d446";
      lastModified = 1717159533;
      narHash = "sha256-oamiKNfr2MS6yH64rUn99mIZjc45nGJlj9eGth/3Xuw=";
    };
    unflake_github_numtide_blueprint = {
      type = "github";
      owner = "numtide";
      repo = "blueprint";
      rev = "56131e8628f173d24a27f6d27c0215eff57e40dd";
      lastModified = 1776249299;
      narHash = "sha256-Dt9t1TGRmJFc0xVYhttNBD6QsAgHOHCArqGa0AyjrJY=";
    };
    unflake_github_numtide_devshell = {
      type = "github";
      owner = "numtide";
      repo = "devshell";
      rev = "255a2b1725a20d060f566e4755dbf571bbbb5f76";
      lastModified = 1768818222;
      narHash = "sha256-460jc0+CZfyaO8+w8JNtlClB2n4ui1RbHfPTLkpwhU8=";
    };
    unflake_github_numtide_flake-utils = {
      type = "github";
      owner = "numtide";
      repo = "flake-utils";
      rev = "11707dc2f618dd54ca8739b309ec4fc024de578b";
      lastModified = 1731533236;
      narHash = "sha256-l0KFg5HjrsfsO/JpG+r7fRrqm12kzFHyUHqHCVpMMbI=";
    };
    unflake_github_numtide_treefmt-nix = {
      type = "github";
      owner = "numtide";
      repo = "treefmt-nix";
      rev = "790751ff7fd3801feeaf96d7dc416a8d581265ba";
      lastModified = 1775636079;
      narHash = "sha256-pc20NRoMdiar8oPQceQT47UUZMBTiMdUuWrYu2obUP0=";
    };
    unflake_github_oxalica_rust-overlay = {
      type = "github";
      owner = "oxalica";
      repo = "rust-overlay";
      rev = "672fa5fc5608d5cd82286a6f69aaf84a40b4fe41";
      lastModified = 1779333539;
      narHash = "sha256-lpmN2lrBDZDPjov2cbD3bOOJsI0fkKolKXasYPCqSys=";
    };
    unflake_github_pyproject-nix_build-system-pkgs = {
      type = "github";
      owner = "pyproject-nix";
      repo = "build-system-pkgs";
      rev = "ffaa2161dd5d63e0e94591f86b54fc239660fb2e";
      lastModified = 1776659114;
      narHash = "sha256-qapCOQmR++yZSY43dzrp3wCrkOTLpod+ONtJWBk6iKU=";
    };
    unflake_github_pyproject-nix_pyproject-nix = {
      type = "github";
      owner = "pyproject-nix";
      repo = "pyproject.nix";
      rev = "a228447c3e179d477c1b6246ef3efa8cfe3c469a";
      lastModified = 1778901413;
      narHash = "sha256-GSKXTAnFqRAMlZkJrIPcQMYf+lpMr66K3i60mB9STvc=";
    };
    unflake_github_pyproject-nix_uv2nix = {
      type = "github";
      owner = "pyproject-nix";
      repo = "uv2nix";
      rev = "69aec536f6d1acc415ed2e20299312802aba98c6";
      lastModified = 1779269674;
      narHash = "sha256-P1LHCRdYpdtHAEzuEsNHrI6d9mVPl5a2fyFDZGHNVbI=";
    };
    unflake_github_rasmus-kirk_website-builder = {
      type = "github";
      owner = "rasmus-kirk";
      repo = "website-builder";
      rev = "896af41c1a01f934799356f1f51cfddff2abda82";
      lastModified = 1771957511;
      narHash = "sha256-MxpsyVQguwmeN40gblvcYLtL4xiriGYB6UyP+JergpQ=";
    };
    unflake_github_rossng_crate2nix_rev_ba5dd398e31ee422fbe021767eb83b0650303a6e = {
      type = "github";
      owner = "rossng";
      repo = "crate2nix";
      rev = "ba5dd398e31ee422fbe021767eb83b0650303a6e";
      lastModified = 1772186516;
      narHash = "sha256-8s28pzmQ6TOIUzznwFibtW1CMieMUl1rYJIxoQYor58=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-degoog-git_ref_0-18-0_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/degoog.git";
      ref = "0.18.0";
      rev = "781545eb198a9698484cd358ae9359a0dabee0e3";
      shallow = true;
      lastModified = 1779220217;
      narHash = "sha256-aY5srxyBhcjNWZjilrcr3NrZmyn7cvJZNPAumbBTzp0=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-NUR-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/NUR.git";
      ref = "main";
      rev = "0eb289ecf974255757de0c80d04ce2685a36fb14";
      shallow = true;
      lastModified = 1779391762;
      narHash = "sha256-aAkn8CS7VMVXdi+MrUDblyVNzykQys/1RWbfVwdyMZ0=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-default-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/default.git";
      ref = "main";
      rev = "da67096a3b9bf56a91d16901293e51ba5b49a27e";
      shallow = true;
      lastModified = 1681028828;
      narHash = "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-fenix-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/fenix.git";
      ref = "main";
      rev = "a6ebca03f87958a09065959897223790014cdcac";
      shallow = true;
      lastModified = 1779357702;
      narHash = "sha256-QGu9ycXwaaqUzDkP7bcanTjGhuqlUNmjh1jLUPjDHgw=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-flake-file-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/flake-file.git";
      ref = "main";
      rev = "c58eb27d9434e5be0c8693f1eb18d47035bc21ba";
      shallow = true;
      lastModified = 1779051720;
      narHash = "sha256-+jbXnODsR19pFKB0x/6kHhFgW6yV6N+CGClFr45eDU8=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-hexecute-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/hexecute.git";
      ref = "main";
      rev = "df00365964ed2f7144f364ee1bdbefec81334583";
      shallow = true;
      lastModified = 1778089142;
      narHash = "sha256-hiLMu/3QznCgKcfhS1E4JzbIe3XP2/c90eWssum3qhE=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-kaneo-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/kaneo.git";
      ref = "main";
      rev = "0f39464f5873d0525dd29f533898ecc323431ed4";
      shallow = true;
      lastModified = 1779132347;
      narHash = "sha256-MRXMFRVQjXXidfGbPZxIu9q4doMah1FdMgiBZozDfCs=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-llm-agents-nix-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/llm-agents.nix.git";
      ref = "main";
      rev = "a98bde078e61857e16a41e88587ea4e2a422c354";
      shallow = true;
      lastModified = 1779392924;
      narHash = "sha256-Vj8VxtRg89gwA2ThsxZjj9VJCQlHBIdTdvIcLTgWjGc=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-microvm-nix-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/microvm.nix.git";
      ref = "main";
      rev = "9755fd345bd64d1c75ba12b63089c926dd5d886e";
      shallow = true;
      lastModified = 1779300350;
      narHash = "sha256-slQySSmaIewOxdZXF0/g0GSiVg7vJy209Yjs7fDNms8=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-niri-flake-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/niri-flake.git";
      ref = "main";
      rev = "f539bec9083f42a406db82e3d974162281e69d12";
      shallow = true;
      lastModified = 1779378331;
      narHash = "sha256-A8MBNRY+FDLVJ64HWjrcdbtahlAey3fvca/hu9q07yA=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-nixarr-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/nixarr.git";
      ref = "main";
      rev = "3bde55fe657ee3ec1c2b2c05294ff381cb8f2d43";
      shallow = true;
      lastModified = 1778908661;
      narHash = "sha256-eeRN0ew1VfutaVNxoaYvua7CHoqc7gI5vLPxUL5ko7k=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-nixcord-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/nixcord.git";
      ref = "main";
      rev = "71aabc1e979259508aca5c24696c75fcb27528b9";
      shallow = true;
      lastModified = 1779383854;
      narHash = "sha256-tIeKJnd7Gb7yMxyrZ+q5szbgoegzaTDWzLbZokMifJg=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-nixos-dns-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/nixos-dns.git";
      ref = "main";
      rev = "4fd527b1bb92cff2f80b3297ae68588dbe772c49";
      shallow = true;
      lastModified = 1778345684;
      narHash = "sha256-Q+s91/rtWoE3DIFf5EfNnsDplFia5sgfb/Q+CPsSy1Y=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-octodns-pihole-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/octodns-pihole.git";
      ref = "main";
      rev = "566a863bc67e18ced24906e7838fa6cff0f471be";
      shallow = true;
      lastModified = 1770915826;
      narHash = "sha256-6pUanEEezAIfNtQB7ia0FThzMv99iI84oTtHOmcIxSE=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-pihole6api-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/pihole6api.git";
      ref = "main";
      rev = "e87c651ce0e084bc5f15c529d6103c524ee98d64";
      shallow = true;
      lastModified = 1766505417;
      narHash = "sha256-8vXYZsq9x+1XIXB8c2tBSvQ0qygrwYC9ZKOOfc68apI=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-superpowers-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/superpowers.git";
      ref = "main";
      rev = "f9b088f7b3a6fe9d9a9a98e392ad13c9d47053a4";
      shallow = true;
      lastModified = 1776201211;
      narHash = "sha256-Nbfzvd7h7KrO9OW7W3DdUgDkQW11xSfZylFXLWJ8J5I=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-treefmt-nix-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/treefmt-nix.git";
      ref = "main";
      rev = "790751ff7fd3801feeaf96d7dc416a8d581265ba";
      shallow = true;
      lastModified = 1775636079;
      narHash = "sha256-pc20NRoMdiar8oPQceQT47UUZMBTiMdUuWrYu2obUP0=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-zjstatus-git_ref_main_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/zjstatus.git";
      ref = "main";
      rev = "f7f58bd3cb30352a8da85926636b8ec41770098a";
      shallow = true;
      lastModified = 1776491188;
      narHash = "sha256-sjMs63OaRhwCrl46v1A+K2EJdqnw63Pc7BMnHqiU790=";
    };
    unflake_git_https---git-sr-ht--micampe-fennel-ls-nvim-docs_ref_main = {
      type = "git";
      url = "https://git.sr.ht/~micampe/fennel-ls-nvim-docs";
      ref = "main";
      rev = "a072d3f5d2dd98cf0411cd16446a0f3c96ee7938";
      revCount = 27;
      lastModified = 1777640939;
      narHash = "sha256-DpLNcaH3JRrXO8Ds0ZlzoBQFSaOD8xK5+iYZSICBqao=";
    };
    unflake_git_https---git-sr-ht--watersucks-optnix_ref_main = {
      type = "git";
      url = "https://git.sr.ht/~watersucks/optnix";
      ref = "main";
      rev = "c320dc5494c0caaca9ee4341367618c06a957709";
      revCount = 125;
      lastModified = 1776468647;
      narHash = "sha256-zx5O1RyRl6Fq+mvMh+JdS18aXR8644bcN9MKh2fN19M=";
    };
    unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_main = {
      type = "git";
      url = "https://github.com/Supreeeme/xwayland-satellite.git";
      ref = "main";
      rev = "a879e5e0896a326adc79c474bf457b8b99011027";
      revCount = 242;
      lastModified = 1773622265;
      narHash = "sha256-wToKwH7IgWdGLMSIWksEDs4eumR6UbbsuPQ42r0oTXQ=";
    };
    unflake_git_https---github-com-YaLTeR-niri-git_ref_main = {
      type = "git";
      url = "https://github.com/YaLTeR/niri.git";
      ref = "main";
      rev = "4294948cf1c70c50e938383c2c865d7ca455ac7e";
      revCount = 2795;
      lastModified = 1779374863;
      narHash = "sha256-qKWgJ2MUODpg+b8tOwWMdMKREvs8TdGBz63SHaQZCeA=";
    };
    unflake_git_https---github-com-joaovl5-whisper-overlay-git_ref_main = {
      type = "git";
      url = "https://github.com/joaovl5/whisper-overlay.git";
      ref = "main";
      rev = "fbf0501b6a2dab1f9aa408f4b11624f58debb5da";
      revCount = 37;
      lastModified = 1777261856;
      narHash = "sha256-9Y3DiVQnlZr89bLb3AGgK0osaOyEGVUe69uo5FayXoA=";
    };
    unflake_git_ssh---git-git-trll-ing-lav-hermes-agent-git_ref_main = {
      type = "git";
      url = "ssh://git@git.trll.ing/lav/hermes-agent.git";
      ref = "main";
      rev = "db84a78e618bf973ffc403ed2e1f8162f2591daa";
      revCount = 8389;
      lastModified = 1778846642;
      narHash = "sha256-wJoPWAInmXL5Lu0wLL3eaqdddqFOHP+92NZI7zgSAwI=";
    };
    unflake_git_ssh---git-git-trll-ing-lav-sane_fnlfmt-git_ref_main = {
      type = "git";
      url = "ssh://git@git.trll.ing/lav/sane_fnlfmt.git";
      ref = "main";
      rev = "87b02d05d870c66730f9dd39f3af26a1b46f1172";
      revCount = 137;
      lastModified = 1778866012;
      narHash = "sha256-BTHttm/PmXdA/Lvg5io90ucqi73GFeIdEBnXHam+0wI=";
    };
    unflake_git_ssh---git-github-com-joaovl5-__secrets-git_ref_main = {
      type = "git";
      url = "ssh://git@github.com/joaovl5/__secrets.git";
      ref = "main";
      rev = "9df98552066a2244b4471a1b39f7fad666fb04e3";
      revCount = 48;
      lastModified = 1778145955;
      narHash = "sha256-oWbe+HdIxvyNfrHUHKrh3aIOgMW0fjn6Ez+lMf7It3U=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-deploy-rs-git_ref_master_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/deploy-rs.git";
      ref = "master";
      rev = "77c906c0ba56aabdbc72041bf9111b565cdd6171";
      shallow = true;
      lastModified = 1770019181;
      narHash = "sha256-hwsYgDnby50JNVpTRYlF3UR/Rrpt01OrxVuryF40CFY=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-disko-git_ref_master_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/disko.git";
      ref = "master";
      rev = "65fb947964bd44fc0008faf77d1fcb7a9f40bb32";
      shallow = true;
      lastModified = 1779226674;
      narHash = "sha256-wuOkjI6pRiN4sEn/EPBRnNW5cmcpvd7xtIM8y5LooAs=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-emacs-overlay-git_ref_master_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/emacs-overlay.git";
      ref = "master";
      rev = "c0ee65d473ebdd79e27ae32636054ea89ec990a8";
      shallow = true;
      lastModified = 1779389208;
      narHash = "sha256-nTvPl9e2jnBNsiuQ0I5wq1VOpvVQcJuIynLMssO0LtQ=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-flake-utils-plus-git_ref_master_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/flake-utils-plus.git";
      ref = "master";
      rev = "afcb15b845e74ac5e998358709b2b5fe42a948d1";
      shallow = true;
      lastModified = 1738591040;
      narHash = "sha256-4WNeriUToshQ/L5J+dTSWC5OJIwT39SEP7V7oylndi8=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-hister-git_ref_master_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/hister.git";
      ref = "master";
      rev = "0f9d4f022dd1938fa1b0b410ee24d121481b8f0f";
      shallow = true;
      lastModified = 1779388920;
      narHash = "sha256-6+laKzygw0FLDfYRv681nvFfTv7l3J496MBgVmEP52o=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-home-manager-git_ref_master_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/home-manager.git";
      ref = "master";
      rev = "928d72376949e222ea4f07b44828a55b0136422e";
      shallow = true;
      lastModified = 1779336838;
      narHash = "sha256-n1+l78hJRABp4cQHKeD0BVByT0vZLPqd09Tvoq8Q+d8=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-musnix-git_ref_master_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/musnix.git";
      ref = "master";
      rev = "8548782f0d1d0928daa3fffde8a008f72219a3f3";
      shallow = true;
      lastModified = 1777848538;
      narHash = "sha256-Dj51C0NWsglqRrCpdmMr2nFiYacFOid1Tor4H9yG2HY=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-sops-nix-git_ref_master_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/sops-nix.git";
      ref = "master";
      rev = "c591bf665727040c6cc5cb409079acb22dcce33c";
      shallow = true;
      lastModified = 1777944972;
      narHash = "sha256-VfGRo1qTBKOe3s2gOv8LSoA6Fk19PvBlwQ1ECN0Evn8=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-tree-sitter-kanata-git_ref_master_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/tree-sitter-kanata.git";
      ref = "master";
      rev = "af53b4c35d6faa3b4ba7c317fb795a6eb679b42a";
      shallow = true;
      lastModified = 1758479938;
      narHash = "sha256-+7EiIkcSe4raApw1H1iQJC2aILLdSrM7Y3tAswbCO1o=";
    };
    unflake_git_https---github-com-edolstra-flake-compat-git_ref_master = {
      type = "git";
      url = "https://github.com/edolstra/flake-compat.git";
      ref = "master";
      rev = "5edf11c44bc78a0d334f6334cdaf7d60d732daab";
      revCount = 91;
      lastModified = 1767039857;
      narHash = "sha256-vNpUSpF5Nuw8xvDLj2KCwwksIbjua2LZCqhV1LNRDns=";
    };
    unflake_git_https---github-com-nixos-flake-compat-git_ref_master = {
      type = "git";
      url = "https://github.com/nixos/flake-compat.git";
      ref = "master";
      rev = "5edf11c44bc78a0d334f6334cdaf7d60d732daab";
      revCount = 91;
      lastModified = 1767039857;
      narHash = "sha256-vNpUSpF5Nuw8xvDLj2KCwwksIbjua2LZCqhV1LNRDns=";
    };
    unflake_git_https---github-com-stoeffel-nix-test-runner-git_ref_master = {
      type = "git";
      url = "https://github.com/stoeffel/nix-test-runner.git";
      ref = "master";
      rev = "c45d45b11ecef3eb9d834c3b6304c05c49b06ca2";
      revCount = 59;
      lastModified = 1588761593;
      narHash = "sha256-FKJykltAN/g3eIceJl4SfDnnyuH2jHImhMrXS2KvGIs=";
    };
    unflake_git_ssh---git-git-trll-ing-lav-jcode_ref_master = {
      type = "git";
      url = "ssh://git@git.trll.ing/lav/jcode";
      ref = "master";
      rev = "a8c772ca7b0a8085a5bc9eddba6561fb78e50b45";
      revCount = 3127;
      lastModified = 1778236702;
      narHash = "sha256-Y57eDjJSW+9t4SwZ01pK2Naaw8IqrfU4c63pYFObAsI=";
    };
    unflake_git_https---github-com-rust-lang-rust-analyzer-git_ref_nightly = {
      type = "git";
      url = "https://github.com/rust-lang/rust-analyzer.git";
      ref = "nightly";
      rev = "7f916ab1b1f669cec017960c2d91a9a87b4b7bae";
      revCount = 40004;
      lastModified = 1779303932;
      narHash = "sha256-alMOllPgosTsuXGjhvQvbGH0ekPOZW0QfGTI0NdJtbQ=";
    };
    unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-25-11 = {
      type = "git";
      url = "https://github.com/NixOS/nixpkgs.git";
      ref = "nixos-25.11";
      rev = "687f05a9184cad4eaf905c48b63649e3a86f5433";
      revCount = 912939;
      lastModified = 1779102034;
      narHash = "sha256-vZJZjLo513IeI8hjzHFc6TDezUd4uCE2Eq4SNO3DNNg=";
    };
    unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable = {
      type = "git";
      url = "https://github.com/NixOS/nixpkgs.git";
      ref = "nixos-unstable";
      rev = "d233902339c02a9c334e7e593de68855ad26c4cb";
      revCount = 998534;
      lastModified = 1778869304;
      narHash = "sha256-30sZNZoA1cqF5JNO9fVX+wgiQYjB7HJqqJ4ztCDeBZE=";
    };
    unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable-small = {
      type = "git";
      url = "https://github.com/NixOS/nixpkgs.git";
      ref = "nixos-unstable-small";
      rev = "657e2fa0760e27167cdacb1ec5d84782be312013";
      revCount = 1002800;
      lastModified = 1779350018;
      narHash = "sha256-fHMrI2uuDNdQy0X6vgDdLoAHEMV4phk8OLtNMra7Vyk=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-rumdl-git_ref_v0-1-95_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/rumdl.git";
      ref = "v0.1.95";
      rev = "e2084bd1bc70402a142a6c65475a0b07ae687847";
      shallow = true;
      lastModified = 1779221704;
      narHash = "sha256-EH5E9iBxEOik8ZibQqK8A5PeKhYbUxioY5JJlDAg6W8=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-mardi-gras-git_ref_v0-22-0_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/mardi-gras.git";
      ref = "v0.22.0";
      rev = "98f05f7b1e3e30800e6f8509f5f49e0d2a905d22";
      shallow = true;
      lastModified = 1779039464;
      narHash = "sha256-JBiig+kI2X6SZhEb5mAiacLiMI5nIU0klWlBCBFshMo=";
    };
    unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_v0-7 = {
      type = "git";
      url = "https://github.com/Supreeeme/xwayland-satellite.git";
      ref = "v0.7";
      rev = "838e68b9ef35613524b0a76a569afdaab7d5ce8c";
      revCount = 146;
      lastModified = 1755491097;
      narHash = "sha256-m+9tUfsmBeF2Gn4HWa6vSITZ4Gz1eA1F5Kh62B0N4oE=";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-nix-flatpak-git_ref_v0-7-0_shallow = {
      type = "git";
      url = "ssh://git@git.trll.ing/mirrors/nix-flatpak.git";
      ref = "v0.7.0";
      rev = "440818969ac2cbd77bfe025e884d0aa528991374";
      shallow = true;
      lastModified = 1767983141;
      narHash = "sha256-7ZCulYUD9RmJIDULTRkGLSW1faMpDlPKcbWJLYHoXcs=";
    };
    unflake_git_https---github-com-YaLTeR-niri-git_ref_v25-08 = {
      type = "git";
      url = "https://github.com/YaLTeR/niri.git";
      ref = "v25.08";
      rev = "d85b524d7c07a47345eab434f471f2b7bfa2c9c3";
      revCount = 2362;
      lastModified = 1756556321;
      narHash = "sha256-RLD89dfjN0RVO86C/Mot0T7aduCygPGaYbog566F0Qo=";
    };
    unflake_git_https---spectrum-os-org-git-spectrum = {
      type = "git";
      url = "https://spectrum-os.org/git/spectrum";
      rev = "bc2173e7e82a4a16d2254bb247f697cee49962d9";
      revCount = 1268;
      lastModified = 1779367023;
      narHash = "sha256-+gdIEMrqCBpqmX49pD1GiCtrcXtqWrg33Du/I9vbO5c=";
    };
    unflake_tarball_https---channels-nixos-org-nixos-25-11-nixexprs-tar-xz = {
      type = "tarball";
      url = "https://releases.nixos.org/nixos/25.11/nixos-25.11.11112.687f05a9184c/nixexprs.tar.xz?lastModified=1779102034";
      rev = "687f05a9184cad4eaf905c48b63649e3a86f5433";
      lastModified = 1779102034;
      narHash = "sha256-uTBbAAmkcLK3Fd3RjXG/VX1jkiY0gdh+oqWyB+BjyhI=";
    };
    unflake_tarball_https---channels-nixos-org-nixos-unstable-nixexprs-tar-xz = {
      type = "tarball";
      url = "https://releases.nixos.org/nixos/unstable/nixos-26.05pre998534.d233902339c0/nixexprs.tar.xz?lastModified=1778869304";
      rev = "d233902339c02a9c334e7e593de68855ad26c4cb";
      lastModified = 1778869304;
      narHash = "sha256-VdRy3A14M5vIE882DJcaaR+5wrss9Qsg4YNVbr7uj3k=";
    };
    unflake_tarball_https---flakehub-com-f-edolstra-flake-compat-1-tar-gz = {
      type = "tarball";
      url = "https://api.flakehub.com/f/pinned/edolstra/flake-compat/1.1.0/01948eb7-9cba-704f-bbf3-3fa956735b52/source.tar.gz";
      rev = "ff81ac966bb2cae68946d5ed5fc4994f96d0ffec";
      revCount = 69;
      lastModified = 1733328505;
      narHash = "sha256-NeCCThCEP3eCl2l/+27kNNK7QrwZB1IJCrXfrbv5oqU=";
    };
    unflake_github_ghostty-org_ghostty_flake_false = unflake_github_ghostty-org_ghostty;
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable_flake_false = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    unflake_github_rossng_crate2nix_rev_ba5dd398e31ee422fbe021767eb83b0650303a6e_flake_false = unflake_github_rossng_crate2nix_rev_ba5dd398e31ee422fbe021767eb83b0650303a6e;
    unflake_git_ssh---git-git-trll-ing-mirrors-degoog-git_ref_0-18-0_shallow_flake_false = unflake_git_ssh---git-git-trll-ing-mirrors-degoog-git_ref_0-18-0_shallow;
    unflake_git_ssh---git-git-trll-ing-mirrors-default-git_ref_main_shallow_flake_false = unflake_git_ssh---git-git-trll-ing-mirrors-default-git_ref_main_shallow;
    unflake_git_ssh---git-git-trll-ing-mirrors-kaneo-git_ref_main_shallow_flake_false = unflake_git_ssh---git-git-trll-ing-mirrors-kaneo-git_ref_main_shallow;
    unflake_git_ssh---git-git-trll-ing-mirrors-octodns-pihole-git_ref_main_shallow_flake_false = unflake_git_ssh---git-git-trll-ing-mirrors-octodns-pihole-git_ref_main_shallow;
    unflake_git_ssh---git-git-trll-ing-mirrors-pihole6api-git_ref_main_shallow_flake_false = unflake_git_ssh---git-git-trll-ing-mirrors-pihole6api-git_ref_main_shallow;
    unflake_git_ssh---git-git-trll-ing-mirrors-superpowers-git_ref_main_shallow_flake_false = unflake_git_ssh---git-git-trll-ing-mirrors-superpowers-git_ref_main_shallow;
    unflake_git_https---git-sr-ht--micampe-fennel-ls-nvim-docs_ref_main_flake_false = unflake_git_https---git-sr-ht--micampe-fennel-ls-nvim-docs_ref_main;
    unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_main_flake_false = unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_main;
    unflake_git_https---github-com-YaLTeR-niri-git_ref_main_flake_false = unflake_git_https---github-com-YaLTeR-niri-git_ref_main;
    unflake_git_ssh---git-git-trll-ing-lav-sane_fnlfmt-git_ref_main_flake_false = unflake_git_ssh---git-git-trll-ing-lav-sane_fnlfmt-git_ref_main;
    unflake_git_ssh---git-github-com-joaovl5-__secrets-git_ref_main_flake_false = unflake_git_ssh---git-github-com-joaovl5-__secrets-git_ref_main;
    unflake_git_ssh---git-git-trll-ing-mirrors-tree-sitter-kanata-git_ref_master_shallow_flake_false = unflake_git_ssh---git-git-trll-ing-mirrors-tree-sitter-kanata-git_ref_master_shallow;
    unflake_git_https---github-com-edolstra-flake-compat-git_ref_master_flake_false = unflake_git_https---github-com-edolstra-flake-compat-git_ref_master;
    unflake_git_https---github-com-nixos-flake-compat-git_ref_master_flake_false = unflake_git_https---github-com-nixos-flake-compat-git_ref_master;
    unflake_git_https---github-com-stoeffel-nix-test-runner-git_ref_master_flake_false = unflake_git_https---github-com-stoeffel-nix-test-runner-git_ref_master;
    unflake_git_https---github-com-rust-lang-rust-analyzer-git_ref_nightly_flake_false = unflake_git_https---github-com-rust-lang-rust-analyzer-git_ref_nightly;
    unflake_git_ssh---git-git-trll-ing-mirrors-rumdl-git_ref_v0-1-95_shallow_flake_false = unflake_git_ssh---git-git-trll-ing-mirrors-rumdl-git_ref_v0-1-95_shallow;
    unflake_git_ssh---git-git-trll-ing-mirrors-mardi-gras-git_ref_v0-22-0_shallow_flake_false = unflake_git_ssh---git-git-trll-ing-mirrors-mardi-gras-git_ref_v0-22-0_shallow;
    unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_v0-7_flake_false = unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_v0-7;
    unflake_git_https---github-com-YaLTeR-niri-git_ref_v25-08_flake_false = unflake_git_https---github-com-YaLTeR-niri-git_ref_v25-08;
    unflake_git_https---spectrum-os-org-git-spectrum_flake_false = unflake_git_https---spectrum-os-org-git-spectrum;
  };
  deps = indirect_deps // builtins.mapAttrs (_: spec: builtins.fetchTree spec) specs;
  injections = rec {
    unflake_indirect_nixpkgs = {
    };
    unflake_github_cachix_nix_ref_devenv-2-34 = {
      flake-compat = "unflake_git_https---github-com-nixos-flake-compat-git_ref_master_flake_false";
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      git-hooks-nix = "unflake_github_cachix_git-hooks-nix";
      nixpkgs = "unflake_tarball_https---channels-nixos-org-nixos-25-11-nixexprs-tar-xz";
      nixpkgs-23-11 = "unflake_github_nixos_nixpkgs_rev_a62e6edd6d5e1fa0329b8653c801147986f8d446";
      nixpkgs-regression = "unflake_github_nixos_nixpkgs_rev_215d4d0fd80ca5163643b03a33fde804a29cc1e2";
    };
    unflake_github_cachix_cachix_ref_latest = {
      devenv = "unflake_github_cachix_devenv";
      flake-compat = "unflake_git_https---github-com-edolstra-flake-compat-git_ref_master_flake_false";
      git-hooks = "unflake_github_cachix_git-hooks-nix";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_github_cachix_devenv-nixpkgs_ref_rolling = {
      nixpkgs-src = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable_flake_false";
    };
    unflake_github_cachix_devenv = {
      cachix = "unflake_github_cachix_cachix_ref_latest";
      crate2nix = "unflake_github_rossng_crate2nix_rev_ba5dd398e31ee422fbe021767eb83b0650303a6e_flake_false";
      flake-compat = "unflake_git_https---github-com-edolstra-flake-compat-git_ref_master_flake_false";
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      ghostty = "unflake_github_ghostty-org_ghostty_flake_false";
      git-hooks = "unflake_github_cachix_git-hooks-nix";
      nix = "unflake_github_cachix_nix_ref_devenv-2-34";
      nixd = "unflake_github_nix-community_nixd";
      nixpkgs = "unflake_github_cachix_devenv-nixpkgs_ref_rolling";
      rust-overlay = "unflake_github_oxalica_rust-overlay";
    };
    unflake_github_cachix_git-hooks-nix = {
      flake-compat = "unflake_git_https---github-com-nixos-flake-compat-git_ref_master_flake_false";
      gitignore = "unflake_github_hercules-ci_gitignore-nix";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_github_cachix_pre-commit-hooks-nix = {
      flake-compat = "unflake_git_https---github-com-nixos-flake-compat-git_ref_master_flake_false";
      gitignore = "unflake_github_hercules-ci_gitignore-nix";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_github_hercules-ci_flake-parts = {
      nixpkgs-lib = "unflake_github_nix-community_nixpkgs-lib";
    };
    unflake_github_hercules-ci_gitignore-nix = {
      nixpkgs = "unflake_indirect_nixpkgs";
    };
    unflake_github_ipetkov_crane = {
    };
    unflake_github_jeslie0_npm-lockfile-fix = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_github_maroka-chan_vpn-confinement = {
    };
    unflake_github_nix-community_bun2nix = {
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      systems = "unflake_github_nix-systems_default";
      treefmt-nix = "unflake_github_numtide_treefmt-nix";
    };
    unflake_github_nix-community_crate2nix = {
      cachix = "unflake_github_cachix_cachix_ref_latest";
      devshell = "unflake_github_numtide_devshell";
      flake-compat = "unflake_tarball_https---flakehub-com-f-edolstra-flake-compat-1-tar-gz";
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      nix-test-runner = "unflake_git_https---github-com-stoeffel-nix-test-runner-git_ref_master_flake_false";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
      pre-commit-hooks = "unflake_github_cachix_pre-commit-hooks-nix";
    };
    unflake_github_nix-community_nixd = {
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      nixpkgs = "unflake_tarball_https---channels-nixos-org-nixos-unstable-nixexprs-tar-xz";
      treefmt-nix = "unflake_github_numtide_treefmt-nix";
    };
    unflake_github_nix-community_nixpkgs-lib = {
    };
    unflake_github_nix-community_pyproject-nix = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_github_nix-systems_default = {
    };
    unflake_github_nixos_nixpkgs_ref_nixos-25-11 = {
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = {
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = {
    };
    unflake_github_nixos_nixpkgs_rev_215d4d0fd80ca5163643b03a33fde804a29cc1e2 = {
    };
    unflake_github_nixos_nixpkgs_rev_a62e6edd6d5e1fa0329b8653c801147986f8d446 = {
    };
    unflake_github_numtide_blueprint = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      systems = "unflake_github_nix-systems_default";
    };
    unflake_github_numtide_devshell = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_github_numtide_flake-utils = {
      systems = "unflake_github_nix-systems_default";
    };
    unflake_github_numtide_treefmt-nix = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_github_oxalica_rust-overlay = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_github_pyproject-nix_build-system-pkgs = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      pyproject-nix = "unflake_github_nix-community_pyproject-nix";
      uv2nix = "unflake_github_pyproject-nix_uv2nix";
    };
    unflake_github_pyproject-nix_pyproject-nix = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_github_pyproject-nix_uv2nix = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      pyproject-nix = "unflake_github_pyproject-nix_pyproject-nix";
    };
    unflake_github_rasmus-kirk_website-builder = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-NUR-git_ref_main_shallow = {
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-fenix-git_ref_main_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      rust-analyzer-src = "unflake_git_https---github-com-rust-lang-rust-analyzer-git_ref_nightly_flake_false";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-flake-file-git_ref_main_shallow = {
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-hexecute-git_ref_main_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-llm-agents-nix-git_ref_main_shallow = {
      blueprint = "unflake_github_numtide_blueprint";
      bun2nix = "unflake_github_nix-community_bun2nix";
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
      systems = "unflake_github_nix-systems_default";
      treefmt-nix = "unflake_github_numtide_treefmt-nix";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-microvm-nix-git_ref_main_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      spectrum = "unflake_git_https---spectrum-os-org-git-spectrum_flake_false";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-niri-flake-git_ref_main_shallow = {
      niri-stable = "unflake_git_https---github-com-YaLTeR-niri-git_ref_v25-08_flake_false";
      niri-unstable = "unflake_git_https---github-com-YaLTeR-niri-git_ref_main_flake_false";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      nixpkgs-stable = "unflake_github_nixos_nixpkgs_ref_nixos-25-11";
      xwayland-satellite-stable = "unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_v0-7_flake_false";
      xwayland-satellite-unstable = "unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_main_flake_false";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-nixarr-git_ref_main_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-25-11";
      treefmt-nix = "unflake_github_numtide_treefmt-nix";
      vpnconfinement = "unflake_github_maroka-chan_vpn-confinement";
      website-builder = "unflake_github_rasmus-kirk_website-builder";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-nixcord-git_ref_main_shallow = {
      flake-compat = "unflake_tarball_https---flakehub-com-f-edolstra-flake-compat-1-tar-gz";
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-25-11";
      nixpkgs-nixcord = "unflake_github_nixos_nixpkgs_ref_nixos-25-11";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-nixos-dns-git_ref_main_shallow = {
      flake-compat = "unflake_git_https---github-com-edolstra-flake-compat-git_ref_master_flake_false";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      systems = "unflake_github_nix-systems_default";
      treefmt-nix = "unflake_github_numtide_treefmt-nix";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-treefmt-nix-git_ref_main_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-zjstatus-git_ref_main_shallow = {
      crane = "unflake_github_ipetkov_crane";
      flake-utils = "unflake_github_numtide_flake-utils";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
      rust-overlay = "unflake_github_oxalica_rust-overlay";
    };
    unflake_git_https---git-sr-ht--watersucks-optnix_ref_main = {
      flake-compat = "unflake_git_https---github-com-edolstra-flake-compat-git_ref_master_flake_false";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_git_https---github-com-joaovl5-whisper-overlay-git_ref_main = {
      devshell = "unflake_github_numtide_devshell";
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      pre-commit-hooks = "unflake_github_cachix_pre-commit-hooks-nix";
    };
    unflake_git_ssh---git-git-trll-ing-lav-hermes-agent-git_ref_main = {
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      npm-lockfile-fix = "unflake_github_jeslie0_npm-lockfile-fix";
      pyproject-build-systems = "unflake_github_pyproject-nix_build-system-pkgs";
      pyproject-nix = "unflake_github_pyproject-nix_pyproject-nix";
      uv2nix = "unflake_github_pyproject-nix_uv2nix";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-deploy-rs-git_ref_master_shallow = {
      flake-compat = "unflake_git_https---github-com-edolstra-flake-compat-git_ref_master_flake_false";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
      utils = "unflake_github_numtide_flake-utils";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-disko-git_ref_master_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-emacs-overlay-git_ref_master_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
      nixpkgs-stable = "unflake_github_nixos_nixpkgs_ref_nixos-25-11";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-flake-utils-plus-git_ref_master_shallow = {
      flake-utils = "unflake_github_numtide_flake-utils";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-hister-git_ref_master_shallow = {
      flake-parts = "unflake_github_hercules-ci_flake-parts";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-home-manager-git_ref_master_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-musnix-git_ref_master_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-sops-nix-git_ref_master_shallow = {
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable";
    };
    unflake_git_ssh---git-git-trll-ing-lav-jcode_ref_master = {
      crate2nix = "unflake_github_nix-community_crate2nix";
      nixpkgs = "unflake_github_nixos_nixpkgs_ref_nixos-unstable";
    };
    unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-25-11 = {
    };
    unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable = {
    };
    unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable-small = {
    };
    unflake_git_ssh---git-git-trll-ing-mirrors-nix-flatpak-git_ref_v0-7-0_shallow = {
    };
    unflake_tarball_https---channels-nixos-org-nixos-25-11-nixexprs-tar-xz = {
    };
    unflake_tarball_https---channels-nixos-org-nixos-unstable-nixexprs-tar-xz = {
    };
    unflake_tarball_https---flakehub-com-f-edolstra-flake-compat-1-tar-gz = {
    };
  };
  inject = name: flake_path: subdir:
    let
      inputs = builtins.mapAttrs (_: dep: universe.${dep}) injections.${name} // {
        inherit self;
      };
      sourceInfo = deps.${name};
      outPath = "${sourceInfo.outPath}${subdir}";
      outputs = (import "${sourceInfo.outPath}/${flake_path}").outputs inputs;
      self = outputs // sourceInfo // {
        inherit inputs outputs outPath sourceInfo;
        _type = "flake";
        _flake = true;
      };
    in self;
  universe = rec {
    unflake_indirect_nixpkgs = inject "unflake_indirect_nixpkgs" "flake.nix" "";
    unflake_github_cachix_nix_ref_devenv-2-34 = inject "unflake_github_cachix_nix_ref_devenv-2-34" "flake.nix" "";
    unflake_github_cachix_cachix_ref_latest = inject "unflake_github_cachix_cachix_ref_latest" "flake.nix" "";
    unflake_github_cachix_devenv-nixpkgs_ref_rolling = inject "unflake_github_cachix_devenv-nixpkgs_ref_rolling" "flake.nix" "";
    unflake_github_cachix_devenv = inject "unflake_github_cachix_devenv" "flake.nix" "";
    unflake_github_cachix_git-hooks-nix = inject "unflake_github_cachix_git-hooks-nix" "flake.nix" "";
    unflake_github_cachix_pre-commit-hooks-nix = inject "unflake_github_cachix_pre-commit-hooks-nix" "flake.nix" "";
    unflake_github_ghostty-org_ghostty_flake_false = deps.unflake_github_ghostty-org_ghostty_flake_false;
    unflake_github_hercules-ci_flake-parts = inject "unflake_github_hercules-ci_flake-parts" "flake.nix" "";
    unflake_github_hercules-ci_gitignore-nix = inject "unflake_github_hercules-ci_gitignore-nix" "flake.nix" "";
    unflake_github_ipetkov_crane = inject "unflake_github_ipetkov_crane" "flake.nix" "";
    unflake_github_jeslie0_npm-lockfile-fix = inject "unflake_github_jeslie0_npm-lockfile-fix" "flake.nix" "";
    unflake_github_maroka-chan_vpn-confinement = inject "unflake_github_maroka-chan_vpn-confinement" "flake.nix" "";
    unflake_github_nix-community_bun2nix = inject "unflake_github_nix-community_bun2nix" "flake.nix" "";
    unflake_github_nix-community_crate2nix = inject "unflake_github_nix-community_crate2nix" "flake.nix" "";
    unflake_github_nix-community_nixd = inject "unflake_github_nix-community_nixd" "flake.nix" "";
    unflake_github_nix-community_nixpkgs-lib = inject "unflake_github_nix-community_nixpkgs-lib" "flake.nix" "";
    unflake_github_nix-community_pyproject-nix = inject "unflake_github_nix-community_pyproject-nix" "flake.nix" "";
    unflake_github_nix-systems_default = inject "unflake_github_nix-systems_default" "flake.nix" "";
    unflake_github_nixos_nixpkgs_ref_nixos-25-11 = inject "unflake_github_nixos_nixpkgs_ref_nixos-25-11" "flake.nix" "";
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = inject "unflake_github_nixos_nixpkgs_ref_nixos-unstable" "flake.nix" "";
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable_flake_false = deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable_flake_false;
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = inject "unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable" "flake.nix" "";
    unflake_github_nixos_nixpkgs_rev_215d4d0fd80ca5163643b03a33fde804a29cc1e2 = inject "unflake_github_nixos_nixpkgs_rev_215d4d0fd80ca5163643b03a33fde804a29cc1e2" "flake.nix" "";
    unflake_github_nixos_nixpkgs_rev_a62e6edd6d5e1fa0329b8653c801147986f8d446 = inject "unflake_github_nixos_nixpkgs_rev_a62e6edd6d5e1fa0329b8653c801147986f8d446" "flake.nix" "";
    unflake_github_numtide_blueprint = inject "unflake_github_numtide_blueprint" "flake.nix" "";
    unflake_github_numtide_devshell = inject "unflake_github_numtide_devshell" "flake.nix" "";
    unflake_github_numtide_flake-utils = inject "unflake_github_numtide_flake-utils" "flake.nix" "";
    unflake_github_numtide_treefmt-nix = inject "unflake_github_numtide_treefmt-nix" "flake.nix" "";
    unflake_github_oxalica_rust-overlay = inject "unflake_github_oxalica_rust-overlay" "flake.nix" "";
    unflake_github_pyproject-nix_build-system-pkgs = inject "unflake_github_pyproject-nix_build-system-pkgs" "flake.nix" "";
    unflake_github_pyproject-nix_pyproject-nix = inject "unflake_github_pyproject-nix_pyproject-nix" "flake.nix" "";
    unflake_github_pyproject-nix_uv2nix = inject "unflake_github_pyproject-nix_uv2nix" "flake.nix" "";
    unflake_github_rasmus-kirk_website-builder = inject "unflake_github_rasmus-kirk_website-builder" "flake.nix" "";
    unflake_github_rossng_crate2nix_rev_ba5dd398e31ee422fbe021767eb83b0650303a6e_flake_false = deps.unflake_github_rossng_crate2nix_rev_ba5dd398e31ee422fbe021767eb83b0650303a6e_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-degoog-git_ref_0-18-0_shallow_flake_false = deps.unflake_git_ssh---git-git-trll-ing-mirrors-degoog-git_ref_0-18-0_shallow_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-NUR-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-NUR-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-default-git_ref_main_shallow_flake_false = deps.unflake_git_ssh---git-git-trll-ing-mirrors-default-git_ref_main_shallow_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-fenix-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-fenix-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-flake-file-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-flake-file-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-hexecute-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-hexecute-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-kaneo-git_ref_main_shallow_flake_false = deps.unflake_git_ssh---git-git-trll-ing-mirrors-kaneo-git_ref_main_shallow_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-llm-agents-nix-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-llm-agents-nix-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-microvm-nix-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-microvm-nix-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-niri-flake-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-niri-flake-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-nixarr-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-nixarr-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-nixcord-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-nixcord-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-nixos-dns-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-nixos-dns-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-octodns-pihole-git_ref_main_shallow_flake_false = deps.unflake_git_ssh---git-git-trll-ing-mirrors-octodns-pihole-git_ref_main_shallow_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-pihole6api-git_ref_main_shallow_flake_false = deps.unflake_git_ssh---git-git-trll-ing-mirrors-pihole6api-git_ref_main_shallow_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-superpowers-git_ref_main_shallow_flake_false = deps.unflake_git_ssh---git-git-trll-ing-mirrors-superpowers-git_ref_main_shallow_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-treefmt-nix-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-treefmt-nix-git_ref_main_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-zjstatus-git_ref_main_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-zjstatus-git_ref_main_shallow" "flake.nix" "";
    unflake_git_https---git-sr-ht--micampe-fennel-ls-nvim-docs_ref_main_flake_false = deps.unflake_git_https---git-sr-ht--micampe-fennel-ls-nvim-docs_ref_main_flake_false;
    unflake_git_https---git-sr-ht--watersucks-optnix_ref_main = inject "unflake_git_https---git-sr-ht--watersucks-optnix_ref_main" "flake.nix" "";
    unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_main_flake_false = deps.unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_main_flake_false;
    unflake_git_https---github-com-YaLTeR-niri-git_ref_main_flake_false = deps.unflake_git_https---github-com-YaLTeR-niri-git_ref_main_flake_false;
    unflake_git_https---github-com-joaovl5-whisper-overlay-git_ref_main = inject "unflake_git_https---github-com-joaovl5-whisper-overlay-git_ref_main" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-lav-hermes-agent-git_ref_main = inject "unflake_git_ssh---git-git-trll-ing-lav-hermes-agent-git_ref_main" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-lav-sane_fnlfmt-git_ref_main_flake_false = deps.unflake_git_ssh---git-git-trll-ing-lav-sane_fnlfmt-git_ref_main_flake_false;
    unflake_git_ssh---git-github-com-joaovl5-__secrets-git_ref_main_flake_false = deps.unflake_git_ssh---git-github-com-joaovl5-__secrets-git_ref_main_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-deploy-rs-git_ref_master_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-deploy-rs-git_ref_master_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-disko-git_ref_master_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-disko-git_ref_master_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-emacs-overlay-git_ref_master_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-emacs-overlay-git_ref_master_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-flake-utils-plus-git_ref_master_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-flake-utils-plus-git_ref_master_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-hister-git_ref_master_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-hister-git_ref_master_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-home-manager-git_ref_master_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-home-manager-git_ref_master_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-musnix-git_ref_master_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-musnix-git_ref_master_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-sops-nix-git_ref_master_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-sops-nix-git_ref_master_shallow" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-tree-sitter-kanata-git_ref_master_shallow_flake_false = deps.unflake_git_ssh---git-git-trll-ing-mirrors-tree-sitter-kanata-git_ref_master_shallow_flake_false;
    unflake_git_https---github-com-edolstra-flake-compat-git_ref_master_flake_false = deps.unflake_git_https---github-com-edolstra-flake-compat-git_ref_master_flake_false;
    unflake_git_https---github-com-nixos-flake-compat-git_ref_master_flake_false = deps.unflake_git_https---github-com-nixos-flake-compat-git_ref_master_flake_false;
    unflake_git_https---github-com-stoeffel-nix-test-runner-git_ref_master_flake_false = deps.unflake_git_https---github-com-stoeffel-nix-test-runner-git_ref_master_flake_false;
    unflake_git_ssh---git-git-trll-ing-lav-jcode_ref_master = inject "unflake_git_ssh---git-git-trll-ing-lav-jcode_ref_master" "flake.nix" "";
    unflake_git_https---github-com-rust-lang-rust-analyzer-git_ref_nightly_flake_false = deps.unflake_git_https---github-com-rust-lang-rust-analyzer-git_ref_nightly_flake_false;
    unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-25-11 = inject "unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-25-11" "flake.nix" "";
    unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable = inject "unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable" "flake.nix" "";
    unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable-small = inject "unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable-small" "flake.nix" "";
    unflake_git_ssh---git-git-trll-ing-mirrors-rumdl-git_ref_v0-1-95_shallow_flake_false = deps.unflake_git_ssh---git-git-trll-ing-mirrors-rumdl-git_ref_v0-1-95_shallow_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-mardi-gras-git_ref_v0-22-0_shallow_flake_false = deps.unflake_git_ssh---git-git-trll-ing-mirrors-mardi-gras-git_ref_v0-22-0_shallow_flake_false;
    unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_v0-7_flake_false = deps.unflake_git_https---github-com-Supreeeme-xwayland-satellite-git_ref_v0-7_flake_false;
    unflake_git_ssh---git-git-trll-ing-mirrors-nix-flatpak-git_ref_v0-7-0_shallow = inject "unflake_git_ssh---git-git-trll-ing-mirrors-nix-flatpak-git_ref_v0-7-0_shallow" "flake.nix" "";
    unflake_git_https---github-com-YaLTeR-niri-git_ref_v25-08_flake_false = deps.unflake_git_https---github-com-YaLTeR-niri-git_ref_v25-08_flake_false;
    unflake_git_https---spectrum-os-org-git-spectrum_flake_false = deps.unflake_git_https---spectrum-os-org-git-spectrum_flake_false;
    unflake_tarball_https---channels-nixos-org-nixos-25-11-nixexprs-tar-xz = inject "unflake_tarball_https---channels-nixos-org-nixos-25-11-nixexprs-tar-xz" "flake.nix" "";
    unflake_tarball_https---channels-nixos-org-nixos-unstable-nixexprs-tar-xz = inject "unflake_tarball_https---channels-nixos-org-nixos-unstable-nixexprs-tar-xz" "flake.nix" "";
    unflake_tarball_https---flakehub-com-f-edolstra-flake-compat-1-tar-gz = inject "unflake_tarball_https---flakehub-com-f-edolstra-flake-compat-1-tar-gz" "flake.nix" "";
  };
  inputs = {
    all-systems = universe.unflake_git_ssh---git-git-trll-ing-mirrors-default-git_ref_main_shallow_flake_false;
    degoog-src = universe.unflake_git_ssh---git-git-trll-ing-mirrors-degoog-git_ref_0-18-0_shallow_flake_false;
    deploy-rs = universe.unflake_git_ssh---git-git-trll-ing-mirrors-deploy-rs-git_ref_master_shallow;
    disko = universe.unflake_git_ssh---git-git-trll-ing-mirrors-disko-git_ref_master_shallow;
    emacs-bleeding-edge = universe.unflake_git_ssh---git-git-trll-ing-mirrors-emacs-overlay-git_ref_master_shallow;
    fenix = universe.unflake_git_ssh---git-git-trll-ing-mirrors-fenix-git_ref_main_shallow;
    fennel-ls-nvim-docs = universe.unflake_git_https---git-sr-ht--micampe-fennel-ls-nvim-docs_ref_main_flake_false;
    flake-file = universe.unflake_git_ssh---git-git-trll-ing-mirrors-flake-file-git_ref_main_shallow;
    fup = universe.unflake_git_ssh---git-git-trll-ing-mirrors-flake-utils-plus-git_ref_master_shallow;
    hermes-agent = universe.unflake_git_ssh---git-git-trll-ing-lav-hermes-agent-git_ref_main;
    hexecute = universe.unflake_git_ssh---git-git-trll-ing-mirrors-hexecute-git_ref_main_shallow;
    hister = universe.unflake_git_ssh---git-git-trll-ing-mirrors-hister-git_ref_master_shallow;
    hm = universe.unflake_git_ssh---git-git-trll-ing-mirrors-home-manager-git_ref_master_shallow;
    jcode = universe.unflake_git_ssh---git-git-trll-ing-lav-jcode_ref_master;
    kaneo-src = universe.unflake_git_ssh---git-git-trll-ing-mirrors-kaneo-git_ref_main_shallow_flake_false;
    llm-agents = universe.unflake_git_ssh---git-git-trll-ing-mirrors-llm-agents-nix-git_ref_main_shallow;
    mardi-gras-src = universe.unflake_git_ssh---git-git-trll-ing-mirrors-mardi-gras-git_ref_v0-22-0_shallow_flake_false;
    microvm = universe.unflake_git_ssh---git-git-trll-ing-mirrors-microvm-nix-git_ref_main_shallow;
    musnix = universe.unflake_git_ssh---git-git-trll-ing-mirrors-musnix-git_ref_master_shallow;
    mysecrets = universe.unflake_git_ssh---git-github-com-joaovl5-__secrets-git_ref_main_flake_false;
    niri = universe.unflake_git_ssh---git-git-trll-ing-mirrors-niri-flake-git_ref_main_shallow;
    nix-flatpak = universe.unflake_git_ssh---git-git-trll-ing-mirrors-nix-flatpak-git_ref_v0-7-0_shallow;
    nixarr = universe.unflake_git_ssh---git-git-trll-ing-mirrors-nixarr-git_ref_main_shallow;
    nixcord = universe.unflake_git_ssh---git-git-trll-ing-mirrors-nixcord-git_ref_main_shallow;
    nixos-dns = universe.unflake_git_ssh---git-git-trll-ing-mirrors-nixos-dns-git_ref_main_shallow;
    nixpkgs = universe.unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable;
    nur = universe.unflake_git_ssh---git-git-trll-ing-mirrors-NUR-git_ref_main_shallow;
    octodns-pihole-src = universe.unflake_git_ssh---git-git-trll-ing-mirrors-octodns-pihole-git_ref_main_shallow_flake_false;
    optnix = universe.unflake_git_https---git-sr-ht--watersucks-optnix_ref_main;
    pihole6api-src = universe.unflake_git_ssh---git-git-trll-ing-mirrors-pihole6api-git_ref_main_shallow_flake_false;
    rumdl-src = universe.unflake_git_ssh---git-git-trll-ing-mirrors-rumdl-git_ref_v0-1-95_shallow_flake_false;
    sane-fnlfmt-src = universe.unflake_git_ssh---git-git-trll-ing-lav-sane_fnlfmt-git_ref_main_flake_false;
    sops-nix = universe.unflake_git_ssh---git-git-trll-ing-mirrors-sops-nix-git_ref_master_shallow;
    stable = universe.unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-25-11;
    superpowers = universe.unflake_git_ssh---git-git-trll-ing-mirrors-superpowers-git_ref_main_shallow_flake_false;
    tree-sitter-kanata = universe.unflake_git_ssh---git-git-trll-ing-mirrors-tree-sitter-kanata-git_ref_master_shallow_flake_false;
    treefmt-nix = universe.unflake_git_ssh---git-git-trll-ing-mirrors-treefmt-nix-git_ref_main_shallow;
    unstable = universe.unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable;
    unstable-small = universe.unflake_git_https---github-com-NixOS-nixpkgs-git_ref_nixos-unstable-small;
    whisper-overlay = universe.unflake_git_https---github-com-joaovl5-whisper-overlay-git_ref_main;
    zjstatus = universe.unflake_git_ssh---git-git-trll-ing-mirrors-zjstatus-git_ref_main_shallow;
  };
in inputs // {
  withInputs = fn: let outputs = fn (inputs // { inherit self; }); self = outputs // {
    inherit inputs outputs;
    _type = "flake";
    outPath = builtins.toString ./.;
  }; in self;
  __functor = self: self.withInputs;
  self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
  _unflake = { inherit specs deps injections; };
}
