"""Bounds shared across calendar parsing and presentation."""

SNAPSHOT_SCHEMA = 2
TIMELINE_WIDTH = 2750
POLL_HORIZON_DAYS = 14
MAX_EXPANDED_EVENTS = 1000
MAX_LANES = 1
MAX_ALL_DAY_EVENTS = 5
MAX_FUTURE_EVENTS = 3
MIN_VISIBLE_LABEL_CHARS = 3
