-- [nfnl] fnl/plugins/keys/_groups.fnl
local k = require("lib.keys")
k["register-group!"]("tab", "Tab", k.l("q"), k.icon("\243\176\147\170 ", "blue"))
k["register-group!"]("window", "Window", k.l("w"), k.icon("\243\176\149\158 ", "cyan"))
k["register-group!"]("session", "Session", k.l("ws"), k.icon("X ", "cyan"))
k["register-group!"]("buffer", "Buffer", k.l("b"), k.icon("\243\177\148\188 ", "azure"))
k["register-group!"]("fuzzy", "Fuzzy", k.l("f"), k.icon("\240\159\157\147 ", "yellow"))
k["register-group!"]("git", "Git", k.l("g"), k.icon("\239\132\166 ", "orange"))
k["register-group!"]("code", "Code", k.l("c"), k.icon("\238\170\133 ", "green"))
k["register-group!"]("diagnostics", "Messages", k.l("x"), k.icon("\240\159\157\176 ", "red"))
k["register-group!"]("debug", "Debug", k.l("d"), k.icon("\243\176\163\137 ", "purple"))
k["register-group!"]("repl", "REPL", k.l("r"), k.icon("\243\176\181\137 ", "green"))
k["register-group!"]("ai", "AI", k.l("a"), k.icon("\238\176\144 ", "purple"))
k["register-group!"]("meta", "Meta", k.l("_"), k.icon("\238\171\184 ", "grey"))
k["register-group!"]("merge", "Merge", k.l("u"), k.icon("X ", "grey"))
k["register-group!"]("stats", "Stats", k.l("t"), k.icon("X ", "grey"))
k["register-group!"]("action_1", "Actions (1)", ";", k.icon("X ", "red"))
k["register-group!"]("action_2", "Actions (2)", "t", k.icon("X ", "red"))
k["register-group!"]("marks", "Marks", "-", k.icon("X ", "red"))
return true
